# Generated by Django 4.2 on 2023-04-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name', 'index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['course', 'index', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['area', 'index', 'name']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('index', models.IntegerField(default=0)),
                ('video_url', models.URLField(null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.module')),
            ],
            options={
                'ordering': ['module', 'index', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.area'),
        ),
    ]
